# Shell variables
# Generated by 'wal'
wallpaper='/home/jsw/.config/hypr/background.jpg'

# Special
background='#070E19'
foreground='#abbcba'
cursor='#abbcba'

# Colors
color0='#070E19'
color1='#A04D32'
color2='#E0602D'
color3='#A0604E'
color4='#66827E'
color5='#CFA66C'
color6='#EAA864'
color7='#abbcba'
color8='#778382'
color9='#A04D32'
color10='#E0602D'
color11='#A0604E'
color12='#66827E'
color13='#CFA66C'
color14='#EAA864'
color15='#abbcba'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
