--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jsw/.config/hypr/background.jpg"

-- Special
background="#070E19"
foreground="#abbcba"
cursor="#abbcba"

-- Colors
color0="#070E19"
color1="#A04D32"
color2="#E0602D"
color3="#A0604E"
color4="#66827E"
color5="#CFA66C"
color6="#EAA864"
color7="#abbcba"
color8="#778382"
color9="#A04D32"
color10="#E0602D"
color11="#A0604E"
color12="#66827E"
color13="#CFA66C"
color14="#EAA864"
color15="#abbcba"
